### ISSUE TITLE
about feature extraction

### ISSUE THREAD

**Issue by yangwf1** [TencentYoutuResearch/ActionDetection-AFSD#13]
Hi, have you tried to use I3D pre-extracted features? Since this methods involves finetuning of I3D models,
which may result in unfair comparison with other methods.

**Comment by chmxu** [comment]
Hi, we did not conduct experiments with fixed I3D backbone. Enabling the backbone to be finetuned together with predictor is one of our initial targets since it is for sure that finetuning the backbone can boost the performance, while it is extremely hard and inefficient to finetune the backbone in former sota methods. By adopting our structure, unfreezing I3D will not lead to unaffordable computation cost. Maybe you can try to fix the I3D in our model, or to unfreeze the backbone in other methods, to conduct further experiments.
