### ISSUE TITLE
Question about "bounds = [[0, 30], [15, 60], [30, 120], [60, 240], [96, 768], [256, 768]]" 

### ISSUE THREAD

**Issue by Qidian213** [TencentYoutuResearch/ActionDetection-AFSD#9]
https://github.com/TencentYoutuResearch/ActionDetection-AFSD/blob/fcdf2a09003214c1b4ae610a11218d6f4f5a0c23/AFSD/anet/multisegment_loss.py#L128

How to understand the use of bounds?
Thanks!

**Comment by linchuming** [comment]
Bounds can constrain the different pyramid feature to learn actions of different duration, because the duration range of anet dataset is large, and we hope bottom feature to predict actions with short duration and top feature to predict actions with long duration. This design is refer to anchor-free method of object detection and it is useful commonly when the range of object scale is wide.
